#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'PUENTE32' in
 * file './PUENTE32.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'lecturaesc', class 'altera_avalon_pio'
 * The macros are prefixed with 'LECTURAESC_'.
 * The prefix is the slave descriptor.
 */
#define LECTURAESC_COMPONENT_TYPE altera_avalon_pio
#define LECTURAESC_COMPONENT_NAME lecturaesc
#define LECTURAESC_BASE 0xe020
#define LECTURAESC_SPAN 16
#define LECTURAESC_END 0xe02f
#define LECTURAESC_BIT_CLEARING_EDGE_REGISTER 0
#define LECTURAESC_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LECTURAESC_CAPTURE 0
#define LECTURAESC_DATA_WIDTH 16
#define LECTURAESC_DO_TEST_BENCH_WIRING 0
#define LECTURAESC_DRIVEN_SIM_VALUE 0
#define LECTURAESC_EDGE_TYPE NONE
#define LECTURAESC_FREQ 50000000
#define LECTURAESC_HAS_IN 1
#define LECTURAESC_HAS_OUT 1
#define LECTURAESC_HAS_TRI 0
#define LECTURAESC_IRQ_TYPE NONE
#define LECTURAESC_RESET_VALUE 0

/*
 * Macros for device 'escritura', class 'altera_avalon_pio'
 * The macros are prefixed with 'ESCRITURA_'.
 * The prefix is the slave descriptor.
 */
#define ESCRITURA_COMPONENT_TYPE altera_avalon_pio
#define ESCRITURA_COMPONENT_NAME escritura
#define ESCRITURA_BASE 0xf030
#define ESCRITURA_SPAN 16
#define ESCRITURA_END 0xf03f
#define ESCRITURA_BIT_CLEARING_EDGE_REGISTER 0
#define ESCRITURA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ESCRITURA_CAPTURE 0
#define ESCRITURA_DATA_WIDTH 16
#define ESCRITURA_DO_TEST_BENCH_WIRING 0
#define ESCRITURA_DRIVEN_SIM_VALUE 0
#define ESCRITURA_EDGE_TYPE NONE
#define ESCRITURA_FREQ 50000000
#define ESCRITURA_HAS_IN 0
#define ESCRITURA_HAS_OUT 1
#define ESCRITURA_HAS_TRI 0
#define ESCRITURA_IRQ_TYPE NONE
#define ESCRITURA_RESET_VALUE 16383


#endif /* _ALTERA_HPS_0_H_ */
